"""added user_id as foreign key to task table and created relationships

Revision ID: a2694f35a7b2
Revises: d3019aaa4602
Create Date: 2024-02-20 21:52:25.521031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a2694f35a7b2'
down_revision: Union[str, None] = 'd3019aaa4602'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=False))
    op.create_foreign_key(None, 'task', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'user_id')
    # ### end Alembic commands ###
